### ISSUE TITLE
Segmentation faults on set_data.

### ISSUE THREAD

**Issue by punoqun** [zzd1992/GBDTMO#2]
The snippet linked below contains what I've tried so far, excluding the GBDTMO-EX library.
All of my approaches ended up with a Segmentation Error on the set_data lines. 
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV) is the exact output.

https://gist.github.com/punoqun/f1cf23e06721f8d3c3b4ac013d6053d0

I'm running a fresh copy of ubuntu 20.04 and a newly created conda environment with python 3.6. GBDTMO library was compiled with gcc v9.3.

**Comment by zzd1992** [comment]
Sorry, this is my mistake. `y_train` and `y_valid` should be 2D arrays.
You can change the code as:
```python
inp_dim, out_dim = 5, 10
x_train, y_train = np.random.rand(10000, inp_dim), np.random.rand(10000, out_dim)
x_valid, y_valid = np.random.rand(10000, inp_dim), np.random.rand(10000, out_dim)
```
and try again.

If it works, please make sure the input and output array are contiguous with `float64` type for mse loss.

**Comment by punoqun** [comment]
To give the best chance it can get I've updated the code as below, but the segmentation fault issue sadly persists.
```
out_dim = 10
inp_dim = 5
params = {"max_depth": 5, "lr": 0.1, 'loss': b"mse"}
booster = GBDTMulti(LIB, out_dim=out_dim, params=params)
x_train, y_train = np.random.rand(10000, inp_dim), np.random.rand(10000, out_dim)
x_valid, y_valid = np.random.rand(10000, inp_dim), np.random.rand(10000, out_dim)
x_train = np.ascontiguousarray(x_train, dtype=np.float64)
x_valid = np.ascontiguousarray(x_valid, dtype=np.float64)
y_train = np.ascontiguousarray(y_train, dtype=np.float64)
y_valid = np.ascontiguousarray(y_valid, dtype=np.float64)
booster.set_data((x_train, y_train), (x_valid, y_valid))
booster.train(30)
```

**Comment by punoqun** [comment]
Apparently, it's caused by the multithreading of the set_bins method, is there any way to limit the number of threads the code can use?
I'm running this on a 12-threaded machine if it's caused by that maybe limiting the thread count to 8 can be a workaround.

Fatal Python error: Segmentation fault

Thread 0x00007fe29f0b0700 (most recent call first):
  File "/home/peepo/anaconda3/envs/gbdtmo/lib/python3.6/multiprocessing/connection.py", line 379 in _recv
  File "/home/peepo/anaconda3/envs/gbdtmo/lib/python3.6/multiprocessing/connection.py", line 407 in _recv_bytes
  File "/home/peepo/anaconda3/envs/gbdtmo/lib/python3.6/multiprocessing/connection.py", line 250 in recv
  File "/home/peepo/anaconda3/envs/gbdtmo/lib/python3.6/multiprocessing/pool.py", line 463 in _handle_results
  File "/home/peepo/anaconda3/envs/gbdtmo/lib/python3.6/threading.py", line 864 in run
  File "/home/peepo/anaconda3/envs/gbdtmo/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/home/peepo/anaconda3/envs/gbdtmo/lib/python3.6/threading.py", line 884 in _bootstrap

Thread 0x00007fe29a8af700 (most recent call first):
  File "/home/peepo/anaconda3/envs/gbdtmo/lib/python3.6/threading.py", line 295 in wait
  File "/home/peepo/anaconda3/envs/gbdtmo/lib/python3.6/queue.py", line 164 in get
  File "/home/peepo/anaconda3/envs/gbdtmo/lib/python3.6/multiprocessing/pool.py", line 415 in _handle_tasks
  File "/home/peepo/anaconda3/envs/gbdtmo/lib/python3.6/threading.py", line 864 in run
  File "/home/peepo/anaconda3/envs/gbdtmo/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/home/peepo/anaconda3/envs/gbdtmo/lib/python3.6/threading.py", line 884 in _bootstrap

Thread 0x00007fe2980ae700 (most recent call first):
  File "/home/peepo/anaconda3/envs/gbdtmo/lib/python3.6/multiprocessing/pool.py", line 406 in _handle_workers
  File "/home/peepo/anaconda3/envs/gbdtmo/lib/python3.6/threading.py", line 864 in run
  File "/home/peepo/anaconda3/envs/gbdtmo/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/home/peepo/anaconda3/envs/gbdtmo/lib/python3.6/threading.py", line 884 in _bootstrap

Current thread 0x00007fe2cd61b740 (most recent call first):
  File "/home/peepo/PycharmProjects/GBDTMO/gbdtmo/gbdtmo.py", line 22 in _set_bin
  File "/home/peepo/PycharmProjects/GBDTMO/gbdtmo/gbdtmo.py", line 165 in set_data
  File "/home/peepo/PycharmProjects/GBDTMO-trials/main.py", line 22 in gbdtmo_example
  File "/home/peepo/PycharmProjects/GBDTMO-trials/main.py", line 60 in <module>

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

**Comment by zzd1992** [comment]
Please set `num_threads` to 1 in `params`. For more information, you can read the docs.

Avoid using anaconda is another potential solution.

**Comment by zzd1992** [comment]
Here is the code using multi-thread in `gbdtmo/histogram.py`:
```python
def get_bins_maps(x: np.array, max_bins: int, threads: int =1) -> (list, np.array):
    out = []
    if threads==1:
        for i in range(x.shape[-1]):
            out.append(_get_bins_maps(x[:, i], max_bins))
    else:
        x = list(np.transpose(x))
        pool = Pool(threads)
        f = partial(_get_bins_maps, max_bins=max_bins)
        out = pool.map(f, x)
        pool.close()
```

You can also modify it and re-install.

**Comment by punoqun** [comment]
It was apparently caused by conda, I got it working. Thank you so much for the help.

**Comment by betterenvi** [comment]
Not using Anaconda, but still got an error: "segmentation fault  /usr/local/bin/python3.9".

Detail:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/gbdtmo/gbdtmo.py", line 164, in set_data
    self.bins, self.maps = get_bins_maps(self.data, self.max_bins, self.num_threads)
  File "/usr/local/lib/python3.9/site-packages/gbdtmo/histogram.py", line 52, in get_bins_maps
    out.append(_get_bins_maps(x[:, i], max_bins))
  File "/usr/local/lib/python3.9/site-packages/gbdtmo/histogram.py", line 42, in _get_bins_maps
    bins = construct_bin_column(x_column, max_bins)
  File "/usr/local/lib/python3.9/site-packages/numba/core/dispatcher.py", line 439, in _compile_for_args
    raise e
  File "/usr/local/lib/python3.9/site-packages/numba/core/dispatcher.py", line 372, in _compile_for_args
    return_val = self.compile(tuple(argtypes))
  File "/usr/local/lib/python3.9/site-packages/numba/core/dispatcher.py", line 909, in compile
    cres = self._compiler.compile(args, return_type)
  File "/usr/local/lib/python3.9/site-packages/numba/core/dispatcher.py", line 79, in compile
    status, retval = self._compile_cached(args, return_type)
  File "/usr/local/lib/python3.9/site-packages/numba/core/dispatcher.py", line 93, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/usr/local/lib/python3.9/site-packages/numba/core/dispatcher.py", line 106, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler.py", line 604, in compile_extra
    pipeline = pipeline_class(typingctx, targetctx, library,
  File "/usr/local/lib/python3.9/site-packages/numba/core/compiler.py", line 310, in __init__
    targetctx.refresh()
  File "/usr/local/lib/python3.9/site-packages/numba/core/base.py", line 284, in refresh
    self.load_additional_registries()
  File "/usr/local/lib/python3.9/site-packages/numba/core/cpu.py", line 78, in load_additional_registries
    numba.core.entrypoints.init_all()
AttributeError: module 'numba' has no attribute 'core'
```

**Comment by zzd1992** [comment]
> Not using Anaconda, but still got an error: "segmentation fault /usr/local/bin/python3.9".


Your `numba` version might be not satisfied.
On my device, it is `0.42.0` which is old.
You can upgrade or degrade `numba` to solve your problem.

I plan to remove the use of `numba` in the future.

**Comment by samanemami** [comment]
I used `0.53.1` version of numba and got the same segmentation error.
I downgraded to 0.42.0 and received it again.

**Comment by samanemami** [comment]
@zzd1992 Could you also please check your `llvmlite `version?
